# Generated by Django 4.2.4 on 2023-08-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_final', '0002_alter_usuarios_email_alter_usuarios_senha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
