# Generated by Django 4.2.4 on 2023-10-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_final', '0003_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor_Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=50)),
                ('dt_entrada', models.DateField()),
                ('numero_alunos', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
                ('dt_created', models.DateField()),
                ('aluno_vinculado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projeto_final.usuario')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projeto_final.instrutor_parceiro')),
            ],
        ),
    ]
