# Generated by Django 4.2.4 on 2023-11-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Iniciação Científica', 'Iniciação Científica'), ('Mestrando', 'Mestrando'), ('Doutorando', 'Doutorando'), ('Pós-doutorando', 'Pós-doutorando'), ('Professor', 'Professor')], max_length=20)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano_publicacao', models.IntegerField()),
                ('onde_publicado', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=200)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo_pesquisa.integrante')),
            ],
        ),
    ]
