# Generated by Django 4.2.4 on 2023-11-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo_pesquisa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
