# Generated by Django 4.2.4 on 2023-11-05 17:43

from django.db import migrations, models
import grupo_pesquisa.models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo_pesquisa', '0003_alter_publicacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='foto',
            field=models.ImageField(default=1, upload_to=grupo_pesquisa.models.upload_location),
            preserve_default=False,
        ),
    ]
