# Generated by Django 4.2.4 on 2023-11-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo_pesquisa', '0004_alter_integrante_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
